// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"time"
)

type Product struct {
	ID                 int32
	ProductName        string
	ProductDescription string
	Price              int64
	IsActive           bool
	CreatedAt          time.Time
}
